### ISSUE TITLE
The very first example doesnt work

### ISSUE THREAD

**Issue by sneheshs** [SungjoonPark/factor_rotation#9]
Thank you for the great work on the paper!

I wanted to try it out but it failed in the very first example step. I must be doing something wrong. Can you please advise?

In the very first example:
```
import factor_rotation as fr
import numpy as np
import torch

A = np.random.randn(8,2)
L, T = fr.rotate_factors(A, 'varimax', dtype=torch.float64, device=torch.device("cuda"))
print(L)
print(T)
```
**Getting this error**
```
>>> L, T = fr.rotate_factors(A, 'varimax', dtype=torch.float64, device=torch.device("cuda"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/snehesh/DataDrive/PROJECTS/FactorRotation/factor_rotation/_wrappers.py", line 30, in rotate_factors
    return rotate_factors(A, 'CF', dtype, device, 1.0/p, 'orthogonal', **algorithm_kwargs)
  File "/media/snehesh/DataDrive/PROJECTS/FactorRotation/factor_rotation/_wrappers.py", line 49, in rotate_factors
    L, phi, T, table = gr.GPA(A, vgQ=vgQ, T=None, rotation_method=rotation_method, tol=1e-5, dtype=dtype, device=device)
  File "/media/snehesh/DataDrive/PROJECTS/FactorRotation/factor_rotation/_gpa_rotation.py", line 35, in GPA
    s = torch.norm(Gp, p='fro')
TypeError: norm() received an invalid combination of arguments - got (Tensor, p=str), but expected one of:
 * (Tensor input, float p)
      didn't match because some of the arguments have invalid types: (Tensor, p=str)
 * (Tensor input, float p, int dim, bool keepdim, Tensor out)

```

**Comment by sneheshs** [comment]
Not sure why `p='fro'` for `torch.norm` is broken. But I go the hint from https://github.com/pytorch/pytorch/issues/15602. 

By simply commenting it out from `line 35 `of `_gpa_rotation.py`, it seems to work.<br/>
`        s = torch.norm(Gp) # Commenting it out to see if default param works , p='fro')` 

```
>>> import factor_rotation as fr
>>> import numpy as np
>>> import torch
>>> 
>>> A = np.random.randn(8,2)
>>> L, T = fr.rotate_factors(A, 'varimax', dtype=torch.float64, device=torch.device("cuda"))
iter 0 ::	s: 1.3556339 ; alpha: 0.01
iter 1 ::	s: 1.4637947 ; alpha: 0.02
iter 2 ::	s: 1.6671789 ; alpha: 0.04
iter 3 ::	s: 1.953268 ; alpha: 0.08
iter 4 ::	s: 1.5707353 ; alpha: 0.16
iter 5 ::	s: 0.4019254 ; alpha: 0.16
iter 6 ::	s: 0.0420248 ; alpha: 0.16
iter 7 ::	s: 0.0040821 ; alpha: 0.16
iter 8 ::	s: 0.0003962 ; alpha: 0.16
iter 9 ::	s: 3.85e-05 ; alpha: 0.16
iter 10 ::	s: 3.7e-06 ; alpha: 0.16
>>> print(L)
tensor([[-0.2185, -1.3037],
        [ 0.3054,  0.6146],
        [-0.2897,  0.1680],
        [ 0.1549,  0.8225],
        [-0.7926,  0.7896],
        [ 0.0525, -0.3199],
        [ 0.3569, -0.7310],
        [-0.1266,  2.0243]], dtype=torch.float64, device='cuda:0')
>>> print(T)
tensor([[ 0.8261,  0.5635],
        [-0.5635,  0.8261]], dtype=torch.float64, device='cuda:0')
```
You may want to fix this issue in your code.

Best,
Snehesh
